version: '2'

volumes:
  orderer.clsbank.com:
  peer0.banka.com:
  peer0.bankb.com:
  peer0.clsbank.com:

networks:
  clsnet:

services:
  ca.clsbank:
    image: hyperledger/fabric-ca:latest
    container_name: ca_CLSBank
    networks:
      - clsnet
    volumes:
      - ./crypto-config/peerOrganizations/clsbank.com/ca/:/etc/hyperledger/fabric-ca-server-config
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-clsbank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.clsbank.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b0da0c680f53c76225de446f16601476241e4f2985e7423db0669647e8559338_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.clsbank.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b0da0c680f53c76225de446f16601476241e4f2985e7423db0669647e8559338_sk -b admin:adminpw --loglevel info'

  ca.banka:
    image: hyperledger/fabric-ca:latest
    container_name: ca_BankA
    networks:
      - clsnet
    volumes:
      - ./crypto-config/peerOrganizations/banka.com/ca/:/etc/hyperledger/fabric-ca-server-config
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-banka
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.banka.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b6d47d63d9387cb4e168c691f2bd9391be4a0648baaa033db1f10187e62068d5_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.banka.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b6d47d63d9387cb4e168c691f2bd9391be4a0648baaa033db1f10187e62068d5_sk -b admin:adminpw --loglevel info'

  ca.bankb:
    image: hyperledger/fabric-ca:latest
    container_name: ca_BankB
    networks:
      - clsnet
    volumes:
      - ./crypto-config/peerOrganizations/bankb.com/ca/:/etc/hyperledger/fabric-ca-server-config
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bankb
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bankb.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b9d7673319a68a6dbd780fceef668f7e66fd1ea2cdb036404663738cac13800a_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bankb.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b9d7673319a68a6dbd780fceef668f7e66fd1ea2cdb036404663738cac13800a_sk -b admin:adminpw --loglevel info'

  orderer.clsbank.com:
    container_name: orderer.clsbank.com
    networks:
      - clsnet
    image: hyperledger/fabric-orderer:latest
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/clsbank.com/orderers/orderer.clsbank.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/clsbank.com/orderers/orderer.clsbank.com/tls/:/var/hyperledger/orderer/tls
#    - orderer.clsbank.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]    
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric

  peer0.clsbank.com:
    container_name: peer0.clsbank.com
    networks:
      - clsnet
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/clsbank.com/peers/peer0.clsbank.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/clsbank.com/peers/peer0.clsbank.com/tls:/etc/hyperledger/fabric/tls
      - peer0.clsbank.com:/var/hyperledger/production
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fn_clsnet
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.clsbank.com
      - CORE_PEER_ADDRESS=peer0.clsbank.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.clsbank.com:7051
      - CORE_PEER_LOCALMSPID=CLSBankMSP
    command: peer node start

  peer0.banka.com:
    container_name: peer0.banka.com
    networks:
      - clsnet
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/banka.com/peers/peer0.banka.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/banka.com/peers/peer0.banka.com/tls:/etc/hyperledger/fabric/tls
      - peer0.banka.com:/var/hyperledger/production
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fn_clsnet
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.banka.com
      - CORE_PEER_ADDRESS=peer0.banka.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.banka.com:7051
      - CORE_PEER_LOCALMSPID=BankAMSP
    command: peer node start

  peer0.bankb.com:
    container_name: peer0.bankb.com
    networks:
      - clsnet
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/bankb.com/peers/peer0.bankb.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/bankb.com/peers/peer0.bankb.com/tls:/etc/hyperledger/fabric/tls
      - peer0.bankb.com:/var/hyperledger/production
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fn_clsnet
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.bankb.com
      - CORE_PEER_ADDRESS=peer0.bankb.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bankb.com:7051
      - CORE_PEER_LOCALMSPID=BankBMSP
    command: peer node start


#  peer0.banka.com:
#    container_name: peer0.banka.com
#    networks:
#      - clsnet
#
#  peer0.bankb.com:
#    container_name: peer0.bankb.com
#    networks:
#      - clsnet
